### ISSUE TITLE
bootstrap script usage

### ISSUE THREAD

**Issue by RillonDodgers** [evanthegrayt/dotfiles#3]
The bin/bootstrap.sh script when ran without parameters only prints "USAGE:" and none of the actual optional parameters.

**Comment by RillonDodgers** [comment]
![screen shot 2018-05-24 at 7 42 07 am](https://user-images.githubusercontent.com/35751318/40486243-562014ce-5f26-11e8-9022-a120b0cd2e70.png)

**Comment by evanthegrayt** [comment]
Found the issue. Lines 148 and 157, `$USAGE` needs to be in quotes. Will fix asap.

**Comment by evanthegrayt** [comment]
https://github.com/evanthegrayt/dotfiles/pull/4

**Comment by evanthegrayt** [comment]
Fixed. Closing issue.
