### ISSUE TITLE
Git information

### ISSUE THREAD

**Issue by RillonDodgers** [evanthegrayt/dotfiles#9]
Your git information is in the .gitconfig file. So either the readme needs an update to say to change that or it should be removed! 
```
[http]
    sslVerify = false
[user]
	name = Evan Gray
	email = egray1985@gmail.com```

**Comment by evanthegrayt** [comment]
The `README.md` now explicitly states that this might be an issue. This will have to satisfy the issue, as I don't want to remove my `.gitconfig` from my dotfiles. Closing issue.
